const ACTIONS = {
  START: "START",
  STOP: "STOP",

  SLIDE_TEMPO: "SLIDE_TEMPO",
  INCREASE_TEMPO: "INCREASE_TEMPO",
  DECREASE_TEMPO: "DECREASE_TEMPO",

  SLIDE_SWING: "SLIDE_SWING",

  CHANGE_SUBDIVISION: "CHANGE_SUBDIVISION",

  INCREASE_BAR_LENGTH: "INCREASE_BAR_LENGTH",
  DECREASE_BAR_LENGTH: "DECREASE_BAR_LENGTH",

  TOGGLE_STRESSING: "TOGGLE_STRESSING",

  TOGGLE_QUARTER_AUDIOS: "TOGGLE_QUARTER_AUDIOS",
  TOGGLE_SUB_AUDIOS: "TOGGLE_SUB_AUDIOS",
};

export default ACTIONS;
